### ISSUE TITLE
Issue Card Printer plugin for Jira

### ISSUE THREAD

**Issue by Malasree-Narla** [qoomon/Jira-Issue-Card-Printer#32]
Hi,

we have installed Issue Card Printer plugin in Jira.

When we try to print any issue, it gives a pop up saying please select an issue, though we have already selected issues. 
Please Find the attached screenshots 
![issue card printer-1](https://cloud.githubusercontent.com/assets/18441766/14492983/8919ed0e-01a0-11e6-96da-b6aa53d3cee0.PNG)
![issue card printer-2](https://cloud.githubusercontent.com/assets/18441766/14492984/891e74be-01a0-11e6-9ff4-26cfb943e77c.PNG)

Please let us know how to resolve this asap.

Thank you for your support.

**Comment by rpelaez** [comment]
Hi Malasree-Narla,

About the first problem is because there is a bug  when we try to export a filter ( you can see in the URL filter=-1). If you change the URL (removing filter=-1) probably works fine, example  (/issues/?jql=resolution....) 

About the second problem I don't know, probably Bengt can solve it

Best regards!

**Comment by qoomon** [comment]
Sorry i missed it. I will work on it tomorrow.

**Comment by qoomon** [comment]
Should be fixed with dc2ecb8c4f183ea351d118a21ef0b6c3811effea

**Comment by rpelaez** [comment]
It works fine now! Many thanks Bengt!
