### ISSUE TITLE
Epic field is not displayed in Chrome

### ISSUE THREAD

**Issue by mrst** [qoomon/Jira-Issue-Card-Printer#49]
I selected items with an epic and without, but the card printer sadly didn't show the epic.

![2017-01-10_12h36_04](https://cloud.githubusercontent.com/assets/570832/21805041/5e5823b6-d732-11e6-92fe-d358e3b4b566.png)

**Comment by qoomon** [comment]
Thx for reporting.

What Jira Version and what language do you use.

It is is possible that this is a language problem. Because your jira version does not support the new agile api, bookmarlet will fallback to classic api and therefore I only can use the name of the Epic field to access the value, however the fieldname depends on the users language.

**Comment by mrst** [comment]
Sorry for not reacting in time.
You might be right with the language settings, I'm using Jira in English but quite some things are in German in our Jira, so it might well be a language specific problem.
We're in Jira 6.3.15 and Jira Agile 6.7.7.
Thank you for your answer and quick reaction.
